export function PremiumElectricFilters() {
  return (
    <svg
      className="cmd-premium-svg-filters"
      width="0"
      height="0"
      aria-hidden="true"
      focusable="false"
    >
      <defs>
        <filter
          id="cmd-premium-electric-displace"
          colorInterpolationFilters="sRGB"
          x="-20%"
          y="-20%"
          width="140%"
          height="140%"
        >
          <feTurbulence
            type="turbulence"
            baseFrequency="0.02"
            numOctaves="4"
            result="cmdNoiseVertical"
            seed="1"
          />
          <feOffset in="cmdNoiseVertical" dx="0" dy="0" result="cmdOffsetVertical">
            <animate
              attributeName="dy"
              values="700;0"
              dur="6s"
              repeatCount="indefinite"
              calcMode="linear"
            />
          </feOffset>
          <feTurbulence
            type="turbulence"
            baseFrequency="0.02"
            numOctaves="4"
            result="cmdNoiseHorizontal"
            seed="2"
          />
          <feOffset in="cmdNoiseHorizontal" dx="0" dy="0" result="cmdOffsetHorizontal">
            <animate
              attributeName="dx"
              values="490;0"
              dur="6s"
              repeatCount="indefinite"
              calcMode="linear"
            />
          </feOffset>
          <feBlend
            in="cmdOffsetVertical"
            in2="cmdOffsetHorizontal"
            mode="color-dodge"
            result="cmdCombinedNoise"
          />
          <feDisplacementMap
            in="SourceGraphic"
            in2="cmdCombinedNoise"
            scale="22"
            xChannelSelector="R"
            yChannelSelector="B"
          />
        </filter>
      </defs>
    </svg>
  );
}
