export function PremiumElectricFilters() {
  return (
    <svg
      className="cmd-premium-svg-filters"
      width="0"
      height="0"
      aria-hidden="true"
      focusable="false"
    >
      <defs>
        <filter
          id="cmd-premium-electric-displace"
          colorInterpolationFilters="sRGB"
          x="-30%"
          y="-30%"
          width="160%"
          height="160%"
        >
          <feTurbulence
            type="turbulence"
            baseFrequency="0.025"
            numOctaves="3"
            result="cmdElectricNoise"
            seed="1"
          >
            <animate
              attributeName="baseFrequency"
              values="0.025;0.035;0.025"
              dur="1.8s"
              repeatCount="indefinite"
            />
          </feTurbulence>
          <feDisplacementMap
            in="SourceGraphic"
            in2="cmdElectricNoise"
            scale="11"
            xChannelSelector="R"
            yChannelSelector="B"
          />
        </filter>
      </defs>
    </svg>
  );
}
