/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as PoliticasRouteImport } from './routes/politicas'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TiendaRouteImport } from './routes/tienda'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedCatalogoRouteImport } from './routes/_authenticated/catalogo'
import { Route as AuthenticatedDistribuidorRouteImport } from './routes/_authenticated/distribuidor'
import { Route as AuthenticatedProveedorRouteImport } from './routes/_authenticated/proveedor'
import { Route as AuthenticatedRedesSocialesRouteImport } from './routes/_authenticated/redes-sociales'
import { Route as PlataformasIndexRouteImport } from './routes/plataformas/index'
import { Route as PlataformasSlugRouteImport } from './routes/plataformas/$slug'
import { Route as TiendaPublicaSlugRouteImport } from './routes/tienda-publica/$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin/analytics'
import { Route as AuthenticatedAdminInventarioRouteImport } from './routes/_authenticated/admin/inventario'
import { Route as AuthenticatedAdminMiTiendaRouteImport } from './routes/_authenticated/admin/mi-tienda'
import { Route as AuthenticatedAdminPayoutsRouteImport } from './routes/_authenticated/admin/payouts'
import { Route as AuthenticatedAdminPedidosRouteImport } from './routes/_authenticated/admin/pedidos'
import { Route as AuthenticatedAdminPedidosManualesRouteImport } from './routes/_authenticated/admin/pedidos-manuales'
import { Route as AuthenticatedAdminProductosRouteImport } from './routes/_authenticated/admin/productos'
import { Route as AuthenticatedAdminRecargasRouteImport } from './routes/_authenticated/admin/recargas'
import { Route as AuthenticatedAdminServiciosRouteImport } from './routes/_authenticated/admin/servicios'
import { Route as AuthenticatedAdminStockRouteImport } from './routes/_authenticated/admin/stock'
import { Route as AuthenticatedAdminTicketsRouteImport } from './routes/_authenticated/admin/tickets'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'
import { Route as AuthenticatedAdminVencimientosRouteImport } from './routes/_authenticated/admin/vencimientos'
import { Route as AuthenticatedAdminVentasRouteImport } from './routes/_authenticated/admin/ventas'
import { Route as AuthenticatedDistribuidorIndexRouteImport } from './routes/_authenticated/distribuidor/index'
import { Route as AuthenticatedDistribuidorMiTiendaRouteImport } from './routes/_authenticated/distribuidor/mi-tienda'
import { Route as AuthenticatedProveedorIndexRouteImport } from './routes/_authenticated/proveedor/index'
import { Route as AuthenticatedProveedorInventarioRouteImport } from './routes/_authenticated/proveedor/inventario'
import { Route as AuthenticatedProveedorMiTiendaRouteImport } from './routes/_authenticated/proveedor/mi-tienda'
import { Route as AuthenticatedProveedorProductosRouteImport } from './routes/_authenticated/proveedor/productos'
import { Route as AuthenticatedProveedorVentasRouteImport } from './routes/_authenticated/proveedor/ventas'
import { Route as ApiPublicWebhooksFloidRouteImport } from './routes/api/public/webhooks/floid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticasRoute = PoliticasRouteImport.update({
  id: '/politicas',
  path: '/politicas',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TiendaRoute = TiendaRouteImport.update({
  id: '/tienda',
  path: '/tienda',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCatalogoRoute = AuthenticatedCatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDistribuidorRoute =
  AuthenticatedDistribuidorRouteImport.update({
    id: '/distribuidor',
    path: '/distribuidor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProveedorRoute = AuthenticatedProveedorRouteImport.update({
  id: '/proveedor',
  path: '/proveedor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRedesSocialesRoute =
  AuthenticatedRedesSocialesRouteImport.update({
    id: '/redes-sociales',
    path: '/redes-sociales',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const PlataformasIndexRoute = PlataformasIndexRouteImport.update({
  id: '/plataformas/',
  path: '/plataformas/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlataformasSlugRoute = PlataformasSlugRouteImport.update({
  id: '/plataformas/$slug',
  path: '/plataformas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TiendaPublicaSlugRoute = TiendaPublicaSlugRouteImport.update({
  id: '/tienda-publica/$slug',
  path: '/tienda-publica/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminInventarioRoute =
  AuthenticatedAdminInventarioRouteImport.update({
    id: '/inventario',
    path: '/inventario',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMiTiendaRoute =
  AuthenticatedAdminMiTiendaRouteImport.update({
    id: '/mi-tienda',
    path: '/mi-tienda',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPayoutsRoute =
  AuthenticatedAdminPayoutsRouteImport.update({
    id: '/payouts',
    path: '/payouts',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPedidosRoute =
  AuthenticatedAdminPedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPedidosManualesRoute =
  AuthenticatedAdminPedidosManualesRouteImport.update({
    id: '/pedidos-manuales',
    path: '/pedidos-manuales',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProductosRoute =
  AuthenticatedAdminProductosRouteImport.update({
    id: '/productos',
    path: '/productos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRecargasRoute =
  AuthenticatedAdminRecargasRouteImport.update({
    id: '/recargas',
    path: '/recargas',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminServiciosRoute =
  AuthenticatedAdminServiciosRouteImport.update({
    id: '/servicios',
    path: '/servicios',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminStockRoute = AuthenticatedAdminStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminTicketsRoute =
  AuthenticatedAdminTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminVencimientosRoute =
  AuthenticatedAdminVencimientosRouteImport.update({
    id: '/vencimientos',
    path: '/vencimientos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminVentasRoute =
  AuthenticatedAdminVentasRouteImport.update({
    id: '/ventas',
    path: '/ventas',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedDistribuidorIndexRoute =
  AuthenticatedDistribuidorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDistribuidorRoute,
  } as any)
const AuthenticatedDistribuidorMiTiendaRoute =
  AuthenticatedDistribuidorMiTiendaRouteImport.update({
    id: '/mi-tienda',
    path: '/mi-tienda',
    getParentRoute: () => AuthenticatedDistribuidorRoute,
  } as any)
const AuthenticatedProveedorIndexRoute =
  AuthenticatedProveedorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProveedorRoute,
  } as any)
const AuthenticatedProveedorInventarioRoute =
  AuthenticatedProveedorInventarioRouteImport.update({
    id: '/inventario',
    path: '/inventario',
    getParentRoute: () => AuthenticatedProveedorRoute,
  } as any)
const AuthenticatedProveedorMiTiendaRoute =
  AuthenticatedProveedorMiTiendaRouteImport.update({
    id: '/mi-tienda',
    path: '/mi-tienda',
    getParentRoute: () => AuthenticatedProveedorRoute,
  } as any)
const AuthenticatedProveedorProductosRoute =
  AuthenticatedProveedorProductosRouteImport.update({
    id: '/productos',
    path: '/productos',
    getParentRoute: () => AuthenticatedProveedorRoute,
  } as any)
const AuthenticatedProveedorVentasRoute =
  AuthenticatedProveedorVentasRouteImport.update({
    id: '/ventas',
    path: '/ventas',
    getParentRoute: () => AuthenticatedProveedorRoute,
  } as any)
const ApiPublicWebhooksFloidRoute = ApiPublicWebhooksFloidRouteImport.update({
  id: '/api/public/webhooks/floid',
  path: '/api/public/webhooks/floid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/politicas': typeof PoliticasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tienda': typeof TiendaRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/catalogo': typeof AuthenticatedCatalogoRoute
  '/distribuidor': typeof AuthenticatedDistribuidorRouteWithChildren
  '/proveedor': typeof AuthenticatedProveedorRouteWithChildren
  '/redes-sociales': typeof AuthenticatedRedesSocialesRoute
  '/plataformas/$slug': typeof PlataformasSlugRoute
  '/tienda-publica/$slug': typeof TiendaPublicaSlugRoute
  '/plataformas/': typeof PlataformasIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/inventario': typeof AuthenticatedAdminInventarioRoute
  '/admin/mi-tienda': typeof AuthenticatedAdminMiTiendaRoute
  '/admin/payouts': typeof AuthenticatedAdminPayoutsRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/pedidos-manuales': typeof AuthenticatedAdminPedidosManualesRoute
  '/admin/productos': typeof AuthenticatedAdminProductosRoute
  '/admin/recargas': typeof AuthenticatedAdminRecargasRoute
  '/admin/servicios': typeof AuthenticatedAdminServiciosRoute
  '/admin/stock': typeof AuthenticatedAdminStockRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/vencimientos': typeof AuthenticatedAdminVencimientosRoute
  '/admin/ventas': typeof AuthenticatedAdminVentasRoute
  '/distribuidor/mi-tienda': typeof AuthenticatedDistribuidorMiTiendaRoute
  '/proveedor/inventario': typeof AuthenticatedProveedorInventarioRoute
  '/proveedor/mi-tienda': typeof AuthenticatedProveedorMiTiendaRoute
  '/proveedor/productos': typeof AuthenticatedProveedorProductosRoute
  '/proveedor/ventas': typeof AuthenticatedProveedorVentasRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/distribuidor/': typeof AuthenticatedDistribuidorIndexRoute
  '/proveedor/': typeof AuthenticatedProveedorIndexRoute
  '/api/public/webhooks/floid': typeof ApiPublicWebhooksFloidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/politicas': typeof PoliticasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tienda': typeof TiendaRoute
  '/catalogo': typeof AuthenticatedCatalogoRoute
  '/redes-sociales': typeof AuthenticatedRedesSocialesRoute
  '/plataformas/$slug': typeof PlataformasSlugRoute
  '/tienda-publica/$slug': typeof TiendaPublicaSlugRoute
  '/plataformas': typeof PlataformasIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/inventario': typeof AuthenticatedAdminInventarioRoute
  '/admin/mi-tienda': typeof AuthenticatedAdminMiTiendaRoute
  '/admin/payouts': typeof AuthenticatedAdminPayoutsRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/pedidos-manuales': typeof AuthenticatedAdminPedidosManualesRoute
  '/admin/productos': typeof AuthenticatedAdminProductosRoute
  '/admin/recargas': typeof AuthenticatedAdminRecargasRoute
  '/admin/servicios': typeof AuthenticatedAdminServiciosRoute
  '/admin/stock': typeof AuthenticatedAdminStockRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/vencimientos': typeof AuthenticatedAdminVencimientosRoute
  '/admin/ventas': typeof AuthenticatedAdminVentasRoute
  '/distribuidor/mi-tienda': typeof AuthenticatedDistribuidorMiTiendaRoute
  '/proveedor/inventario': typeof AuthenticatedProveedorInventarioRoute
  '/proveedor/mi-tienda': typeof AuthenticatedProveedorMiTiendaRoute
  '/proveedor/productos': typeof AuthenticatedProveedorProductosRoute
  '/proveedor/ventas': typeof AuthenticatedProveedorVentasRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/distribuidor': typeof AuthenticatedDistribuidorIndexRoute
  '/proveedor': typeof AuthenticatedProveedorIndexRoute
  '/api/public/webhooks/floid': typeof ApiPublicWebhooksFloidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/politicas': typeof PoliticasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tienda': typeof TiendaRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/catalogo': typeof AuthenticatedCatalogoRoute
  '/_authenticated/distribuidor': typeof AuthenticatedDistribuidorRouteWithChildren
  '/_authenticated/proveedor': typeof AuthenticatedProveedorRouteWithChildren
  '/_authenticated/redes-sociales': typeof AuthenticatedRedesSocialesRoute
  '/plataformas/$slug': typeof PlataformasSlugRoute
  '/tienda-publica/$slug': typeof TiendaPublicaSlugRoute
  '/plataformas/': typeof PlataformasIndexRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/inventario': typeof AuthenticatedAdminInventarioRoute
  '/_authenticated/admin/mi-tienda': typeof AuthenticatedAdminMiTiendaRoute
  '/_authenticated/admin/payouts': typeof AuthenticatedAdminPayoutsRoute
  '/_authenticated/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/_authenticated/admin/pedidos-manuales': typeof AuthenticatedAdminPedidosManualesRoute
  '/_authenticated/admin/productos': typeof AuthenticatedAdminProductosRoute
  '/_authenticated/admin/recargas': typeof AuthenticatedAdminRecargasRoute
  '/_authenticated/admin/servicios': typeof AuthenticatedAdminServiciosRoute
  '/_authenticated/admin/stock': typeof AuthenticatedAdminStockRoute
  '/_authenticated/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/admin/vencimientos': typeof AuthenticatedAdminVencimientosRoute
  '/_authenticated/admin/ventas': typeof AuthenticatedAdminVentasRoute
  '/_authenticated/distribuidor/mi-tienda': typeof AuthenticatedDistribuidorMiTiendaRoute
  '/_authenticated/proveedor/inventario': typeof AuthenticatedProveedorInventarioRoute
  '/_authenticated/proveedor/mi-tienda': typeof AuthenticatedProveedorMiTiendaRoute
  '/_authenticated/proveedor/productos': typeof AuthenticatedProveedorProductosRoute
  '/_authenticated/proveedor/ventas': typeof AuthenticatedProveedorVentasRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/distribuidor/': typeof AuthenticatedDistribuidorIndexRoute
  '/_authenticated/proveedor/': typeof AuthenticatedProveedorIndexRoute
  '/api/public/webhooks/floid': typeof ApiPublicWebhooksFloidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/politicas'
    | '/reset-password'
    | '/sitemap.xml'
    | '/tienda'
    | '/admin'
    | '/catalogo'
    | '/distribuidor'
    | '/proveedor'
    | '/redes-sociales'
    | '/plataformas/$slug'
    | '/tienda-publica/$slug'
    | '/plataformas/'
    | '/admin/analytics'
    | '/admin/inventario'
    | '/admin/mi-tienda'
    | '/admin/payouts'
    | '/admin/pedidos'
    | '/admin/pedidos-manuales'
    | '/admin/productos'
    | '/admin/recargas'
    | '/admin/servicios'
    | '/admin/stock'
    | '/admin/tickets'
    | '/admin/usuarios'
    | '/admin/vencimientos'
    | '/admin/ventas'
    | '/distribuidor/mi-tienda'
    | '/proveedor/inventario'
    | '/proveedor/mi-tienda'
    | '/proveedor/productos'
    | '/proveedor/ventas'
    | '/admin/'
    | '/distribuidor/'
    | '/proveedor/'
    | '/api/public/webhooks/floid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/politicas'
    | '/reset-password'
    | '/sitemap.xml'
    | '/tienda'
    | '/catalogo'
    | '/redes-sociales'
    | '/plataformas/$slug'
    | '/tienda-publica/$slug'
    | '/plataformas'
    | '/admin/analytics'
    | '/admin/inventario'
    | '/admin/mi-tienda'
    | '/admin/payouts'
    | '/admin/pedidos'
    | '/admin/pedidos-manuales'
    | '/admin/productos'
    | '/admin/recargas'
    | '/admin/servicios'
    | '/admin/stock'
    | '/admin/tickets'
    | '/admin/usuarios'
    | '/admin/vencimientos'
    | '/admin/ventas'
    | '/distribuidor/mi-tienda'
    | '/proveedor/inventario'
    | '/proveedor/mi-tienda'
    | '/proveedor/productos'
    | '/proveedor/ventas'
    | '/admin'
    | '/distribuidor'
    | '/proveedor'
    | '/api/public/webhooks/floid'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/politicas'
    | '/reset-password'
    | '/sitemap.xml'
    | '/tienda'
    | '/_authenticated/admin'
    | '/_authenticated/catalogo'
    | '/_authenticated/distribuidor'
    | '/_authenticated/proveedor'
    | '/_authenticated/redes-sociales'
    | '/plataformas/$slug'
    | '/tienda-publica/$slug'
    | '/plataformas/'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/inventario'
    | '/_authenticated/admin/mi-tienda'
    | '/_authenticated/admin/payouts'
    | '/_authenticated/admin/pedidos'
    | '/_authenticated/admin/pedidos-manuales'
    | '/_authenticated/admin/productos'
    | '/_authenticated/admin/recargas'
    | '/_authenticated/admin/servicios'
    | '/_authenticated/admin/stock'
    | '/_authenticated/admin/tickets'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/admin/vencimientos'
    | '/_authenticated/admin/ventas'
    | '/_authenticated/distribuidor/mi-tienda'
    | '/_authenticated/proveedor/inventario'
    | '/_authenticated/proveedor/mi-tienda'
    | '/_authenticated/proveedor/productos'
    | '/_authenticated/proveedor/ventas'
    | '/_authenticated/admin/'
    | '/_authenticated/distribuidor/'
    | '/_authenticated/proveedor/'
    | '/api/public/webhooks/floid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PoliticasRoute: typeof PoliticasRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TiendaRoute: typeof TiendaRoute
  PlataformasSlugRoute: typeof PlataformasSlugRoute
  TiendaPublicaSlugRoute: typeof TiendaPublicaSlugRoute
  PlataformasIndexRoute: typeof PlataformasIndexRoute
  ApiPublicWebhooksFloidRoute: typeof ApiPublicWebhooksFloidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politicas': {
      id: '/politicas'
      path: '/politicas'
      fullPath: '/politicas'
      preLoaderRoute: typeof PoliticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tienda': {
      id: '/tienda'
      path: '/tienda'
      fullPath: '/tienda'
      preLoaderRoute: typeof TiendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalogo': {
      id: '/_authenticated/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof AuthenticatedCatalogoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/distribuidor': {
      id: '/_authenticated/distribuidor'
      path: '/distribuidor'
      fullPath: '/distribuidor'
      preLoaderRoute: typeof AuthenticatedDistribuidorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proveedor': {
      id: '/_authenticated/proveedor'
      path: '/proveedor'
      fullPath: '/proveedor'
      preLoaderRoute: typeof AuthenticatedProveedorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/redes-sociales': {
      id: '/_authenticated/redes-sociales'
      path: '/redes-sociales'
      fullPath: '/redes-sociales'
      preLoaderRoute: typeof AuthenticatedRedesSocialesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/plataformas/': {
      id: '/plataformas/'
      path: '/plataformas'
      fullPath: '/plataformas/'
      preLoaderRoute: typeof PlataformasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plataformas/$slug': {
      id: '/plataformas/$slug'
      path: '/plataformas/$slug'
      fullPath: '/plataformas/$slug'
      preLoaderRoute: typeof PlataformasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tienda-publica/$slug': {
      id: '/tienda-publica/$slug'
      path: '/tienda-publica/$slug'
      fullPath: '/tienda-publica/$slug'
      preLoaderRoute: typeof TiendaPublicaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/inventario': {
      id: '/_authenticated/admin/inventario'
      path: '/inventario'
      fullPath: '/admin/inventario'
      preLoaderRoute: typeof AuthenticatedAdminInventarioRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/mi-tienda': {
      id: '/_authenticated/admin/mi-tienda'
      path: '/mi-tienda'
      fullPath: '/admin/mi-tienda'
      preLoaderRoute: typeof AuthenticatedAdminMiTiendaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/payouts': {
      id: '/_authenticated/admin/payouts'
      path: '/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AuthenticatedAdminPayoutsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/pedidos': {
      id: '/_authenticated/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AuthenticatedAdminPedidosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/pedidos-manuales': {
      id: '/_authenticated/admin/pedidos-manuales'
      path: '/pedidos-manuales'
      fullPath: '/admin/pedidos-manuales'
      preLoaderRoute: typeof AuthenticatedAdminPedidosManualesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/productos': {
      id: '/_authenticated/admin/productos'
      path: '/productos'
      fullPath: '/admin/productos'
      preLoaderRoute: typeof AuthenticatedAdminProductosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/recargas': {
      id: '/_authenticated/admin/recargas'
      path: '/recargas'
      fullPath: '/admin/recargas'
      preLoaderRoute: typeof AuthenticatedAdminRecargasRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/servicios': {
      id: '/_authenticated/admin/servicios'
      path: '/servicios'
      fullPath: '/admin/servicios'
      preLoaderRoute: typeof AuthenticatedAdminServiciosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/stock': {
      id: '/_authenticated/admin/stock'
      path: '/stock'
      fullPath: '/admin/stock'
      preLoaderRoute: typeof AuthenticatedAdminStockRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/tickets': {
      id: '/_authenticated/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AuthenticatedAdminTicketsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/vencimientos': {
      id: '/_authenticated/admin/vencimientos'
      path: '/vencimientos'
      fullPath: '/admin/vencimientos'
      preLoaderRoute: typeof AuthenticatedAdminVencimientosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/ventas': {
      id: '/_authenticated/admin/ventas'
      path: '/ventas'
      fullPath: '/admin/ventas'
      preLoaderRoute: typeof AuthenticatedAdminVentasRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/distribuidor/': {
      id: '/_authenticated/distribuidor/'
      path: '/'
      fullPath: '/distribuidor/'
      preLoaderRoute: typeof AuthenticatedDistribuidorIndexRouteImport
      parentRoute: typeof AuthenticatedDistribuidorRoute
    }
    '/_authenticated/distribuidor/mi-tienda': {
      id: '/_authenticated/distribuidor/mi-tienda'
      path: '/mi-tienda'
      fullPath: '/distribuidor/mi-tienda'
      preLoaderRoute: typeof AuthenticatedDistribuidorMiTiendaRouteImport
      parentRoute: typeof AuthenticatedDistribuidorRoute
    }
    '/_authenticated/proveedor/': {
      id: '/_authenticated/proveedor/'
      path: '/'
      fullPath: '/proveedor/'
      preLoaderRoute: typeof AuthenticatedProveedorIndexRouteImport
      parentRoute: typeof AuthenticatedProveedorRoute
    }
    '/_authenticated/proveedor/inventario': {
      id: '/_authenticated/proveedor/inventario'
      path: '/inventario'
      fullPath: '/proveedor/inventario'
      preLoaderRoute: typeof AuthenticatedProveedorInventarioRouteImport
      parentRoute: typeof AuthenticatedProveedorRoute
    }
    '/_authenticated/proveedor/mi-tienda': {
      id: '/_authenticated/proveedor/mi-tienda'
      path: '/mi-tienda'
      fullPath: '/proveedor/mi-tienda'
      preLoaderRoute: typeof AuthenticatedProveedorMiTiendaRouteImport
      parentRoute: typeof AuthenticatedProveedorRoute
    }
    '/_authenticated/proveedor/productos': {
      id: '/_authenticated/proveedor/productos'
      path: '/productos'
      fullPath: '/proveedor/productos'
      preLoaderRoute: typeof AuthenticatedProveedorProductosRouteImport
      parentRoute: typeof AuthenticatedProveedorRoute
    }
    '/_authenticated/proveedor/ventas': {
      id: '/_authenticated/proveedor/ventas'
      path: '/ventas'
      fullPath: '/proveedor/ventas'
      preLoaderRoute: typeof AuthenticatedProveedorVentasRouteImport
      parentRoute: typeof AuthenticatedProveedorRoute
    }
    '/api/public/webhooks/floid': {
      id: '/api/public/webhooks/floid'
      path: '/api/public/webhooks/floid'
      fullPath: '/api/public/webhooks/floid'
      preLoaderRoute: typeof ApiPublicWebhooksFloidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminInventarioRoute: typeof AuthenticatedAdminInventarioRoute
  AuthenticatedAdminMiTiendaRoute: typeof AuthenticatedAdminMiTiendaRoute
  AuthenticatedAdminPayoutsRoute: typeof AuthenticatedAdminPayoutsRoute
  AuthenticatedAdminPedidosRoute: typeof AuthenticatedAdminPedidosRoute
  AuthenticatedAdminPedidosManualesRoute: typeof AuthenticatedAdminPedidosManualesRoute
  AuthenticatedAdminProductosRoute: typeof AuthenticatedAdminProductosRoute
  AuthenticatedAdminRecargasRoute: typeof AuthenticatedAdminRecargasRoute
  AuthenticatedAdminServiciosRoute: typeof AuthenticatedAdminServiciosRoute
  AuthenticatedAdminStockRoute: typeof AuthenticatedAdminStockRoute
  AuthenticatedAdminTicketsRoute: typeof AuthenticatedAdminTicketsRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminVencimientosRoute: typeof AuthenticatedAdminVencimientosRoute
  AuthenticatedAdminVentasRoute: typeof AuthenticatedAdminVentasRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
    AuthenticatedAdminInventarioRoute: AuthenticatedAdminInventarioRoute,
    AuthenticatedAdminMiTiendaRoute: AuthenticatedAdminMiTiendaRoute,
    AuthenticatedAdminPayoutsRoute: AuthenticatedAdminPayoutsRoute,
    AuthenticatedAdminPedidosRoute: AuthenticatedAdminPedidosRoute,
    AuthenticatedAdminPedidosManualesRoute:
      AuthenticatedAdminPedidosManualesRoute,
    AuthenticatedAdminProductosRoute: AuthenticatedAdminProductosRoute,
    AuthenticatedAdminRecargasRoute: AuthenticatedAdminRecargasRoute,
    AuthenticatedAdminServiciosRoute: AuthenticatedAdminServiciosRoute,
    AuthenticatedAdminStockRoute: AuthenticatedAdminStockRoute,
    AuthenticatedAdminTicketsRoute: AuthenticatedAdminTicketsRoute,
    AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
    AuthenticatedAdminVencimientosRoute: AuthenticatedAdminVencimientosRoute,
    AuthenticatedAdminVentasRoute: AuthenticatedAdminVentasRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedDistribuidorRouteChildren {
  AuthenticatedDistribuidorMiTiendaRoute: typeof AuthenticatedDistribuidorMiTiendaRoute
  AuthenticatedDistribuidorIndexRoute: typeof AuthenticatedDistribuidorIndexRoute
}

const AuthenticatedDistribuidorRouteChildren: AuthenticatedDistribuidorRouteChildren =
  {
    AuthenticatedDistribuidorMiTiendaRoute:
      AuthenticatedDistribuidorMiTiendaRoute,
    AuthenticatedDistribuidorIndexRoute: AuthenticatedDistribuidorIndexRoute,
  }

const AuthenticatedDistribuidorRouteWithChildren =
  AuthenticatedDistribuidorRoute._addFileChildren(
    AuthenticatedDistribuidorRouteChildren,
  )

interface AuthenticatedProveedorRouteChildren {
  AuthenticatedProveedorInventarioRoute: typeof AuthenticatedProveedorInventarioRoute
  AuthenticatedProveedorMiTiendaRoute: typeof AuthenticatedProveedorMiTiendaRoute
  AuthenticatedProveedorProductosRoute: typeof AuthenticatedProveedorProductosRoute
  AuthenticatedProveedorVentasRoute: typeof AuthenticatedProveedorVentasRoute
  AuthenticatedProveedorIndexRoute: typeof AuthenticatedProveedorIndexRoute
}

const AuthenticatedProveedorRouteChildren: AuthenticatedProveedorRouteChildren =
  {
    AuthenticatedProveedorInventarioRoute:
      AuthenticatedProveedorInventarioRoute,
    AuthenticatedProveedorMiTiendaRoute: AuthenticatedProveedorMiTiendaRoute,
    AuthenticatedProveedorProductosRoute: AuthenticatedProveedorProductosRoute,
    AuthenticatedProveedorVentasRoute: AuthenticatedProveedorVentasRoute,
    AuthenticatedProveedorIndexRoute: AuthenticatedProveedorIndexRoute,
  }

const AuthenticatedProveedorRouteWithChildren =
  AuthenticatedProveedorRoute._addFileChildren(
    AuthenticatedProveedorRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedCatalogoRoute: typeof AuthenticatedCatalogoRoute
  AuthenticatedDistribuidorRoute: typeof AuthenticatedDistribuidorRouteWithChildren
  AuthenticatedProveedorRoute: typeof AuthenticatedProveedorRouteWithChildren
  AuthenticatedRedesSocialesRoute: typeof AuthenticatedRedesSocialesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedCatalogoRoute: AuthenticatedCatalogoRoute,
  AuthenticatedDistribuidorRoute: AuthenticatedDistribuidorRouteWithChildren,
  AuthenticatedProveedorRoute: AuthenticatedProveedorRouteWithChildren,
  AuthenticatedRedesSocialesRoute: AuthenticatedRedesSocialesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PoliticasRoute: PoliticasRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TiendaRoute: TiendaRoute,
  PlataformasSlugRoute: PlataformasSlugRoute,
  TiendaPublicaSlugRoute: TiendaPublicaSlugRoute,
  PlataformasIndexRoute: PlataformasIndexRoute,
  ApiPublicWebhooksFloidRoute: ApiPublicWebhooksFloidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
