/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TiendaRouteImport } from './routes/tienda'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedProveedorRouteImport } from './routes/_authenticated/proveedor'
import { Route as PlataformasIndexRouteImport } from './routes/plataformas/index'
import { Route as PlataformasSlugRouteImport } from './routes/plataformas/$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin/analytics'
import { Route as AuthenticatedAdminInventarioRouteImport } from './routes/_authenticated/admin/inventario'
import { Route as AuthenticatedAdminPayoutsRouteImport } from './routes/_authenticated/admin/payouts'
import { Route as AuthenticatedAdminPedidosRouteImport } from './routes/_authenticated/admin/pedidos'
import { Route as AuthenticatedAdminPedidosManualesRouteImport } from './routes/_authenticated/admin/pedidos-manuales'
import { Route as AuthenticatedAdminProductosRouteImport } from './routes/_authenticated/admin/productos'
import { Route as AuthenticatedAdminProveedoresRouteImport } from './routes/_authenticated/admin/proveedores'
import { Route as AuthenticatedAdminServiciosRouteImport } from './routes/_authenticated/admin/servicios'
import { Route as AuthenticatedAdminStockRouteImport } from './routes/_authenticated/admin/stock'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'
import { Route as AuthenticatedAdminVentasRouteImport } from './routes/_authenticated/admin/ventas'
import { Route as AuthenticatedProveedorIndexRouteImport } from './routes/_authenticated/proveedor/index'
import { Route as AuthenticatedProveedorInventarioRouteImport } from './routes/_authenticated/proveedor/inventario'
import { Route as AuthenticatedProveedorPerfilRouteImport } from './routes/_authenticated/proveedor/perfil'
import { Route as AuthenticatedProveedorVentasRouteImport } from './routes/_authenticated/proveedor/ventas'
import { Route as ApiPublicWebhooksFloidRouteImport } from './routes/api/public/webhooks/floid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TiendaRoute = TiendaRouteImport.update({
  id: '/tienda',
  path: '/tienda',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProveedorRoute = AuthenticatedProveedorRouteImport.update({
  id: '/proveedor',
  path: '/proveedor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PlataformasIndexRoute = PlataformasIndexRouteImport.update({
  id: '/plataformas/',
  path: '/plataformas/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlataformasSlugRoute = PlataformasSlugRouteImport.update({
  id: '/plataformas/$slug',
  path: '/plataformas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminInventarioRoute =
  AuthenticatedAdminInventarioRouteImport.update({
    id: '/inventario',
    path: '/inventario',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPayoutsRoute =
  AuthenticatedAdminPayoutsRouteImport.update({
    id: '/payouts',
    path: '/payouts',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPedidosRoute =
  AuthenticatedAdminPedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPedidosManualesRoute =
  AuthenticatedAdminPedidosManualesRouteImport.update({
    id: '/pedidos-manuales',
    path: '/pedidos-manuales',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProductosRoute =
  AuthenticatedAdminProductosRouteImport.update({
    id: '/productos',
    path: '/productos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProveedoresRoute =
  AuthenticatedAdminProveedoresRouteImport.update({
    id: '/proveedores',
    path: '/proveedores',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminServiciosRoute =
  AuthenticatedAdminServiciosRouteImport.update({
    id: '/servicios',
    path: '/servicios',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminStockRoute = AuthenticatedAdminStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminVentasRoute =
  AuthenticatedAdminVentasRouteImport.update({
    id: '/ventas',
    path: '/ventas',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedProveedorIndexRoute =
  AuthenticatedProveedorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProveedorRoute,
  } as any)
const AuthenticatedProveedorInventarioRoute =
  AuthenticatedProveedorInventarioRouteImport.update({
    id: '/inventario',
    path: '/inventario',
    getParentRoute: () => AuthenticatedProveedorRoute,
  } as any)
const AuthenticatedProveedorPerfilRoute =
  AuthenticatedProveedorPerfilRouteImport.update({
    id: '/perfil',
    path: '/perfil',
    getParentRoute: () => AuthenticatedProveedorRoute,
  } as any)
const AuthenticatedProveedorVentasRoute =
  AuthenticatedProveedorVentasRouteImport.update({
    id: '/ventas',
    path: '/ventas',
    getParentRoute: () => AuthenticatedProveedorRoute,
  } as any)
const ApiPublicWebhooksFloidRoute = ApiPublicWebhooksFloidRouteImport.update({
  id: '/api/public/webhooks/floid',
  path: '/api/public/webhooks/floid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tienda': typeof TiendaRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/proveedor': typeof AuthenticatedProveedorRouteWithChildren
  '/plataformas/$slug': typeof PlataformasSlugRoute
  '/plataformas/': typeof PlataformasIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/inventario': typeof AuthenticatedAdminInventarioRoute
  '/admin/payouts': typeof AuthenticatedAdminPayoutsRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/pedidos-manuales': typeof AuthenticatedAdminPedidosManualesRoute
  '/admin/productos': typeof AuthenticatedAdminProductosRoute
  '/admin/proveedores': typeof AuthenticatedAdminProveedoresRoute
  '/admin/servicios': typeof AuthenticatedAdminServiciosRoute
  '/admin/stock': typeof AuthenticatedAdminStockRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/ventas': typeof AuthenticatedAdminVentasRoute
  '/proveedor/inventario': typeof AuthenticatedProveedorInventarioRoute
  '/proveedor/perfil': typeof AuthenticatedProveedorPerfilRoute
  '/proveedor/ventas': typeof AuthenticatedProveedorVentasRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/proveedor/': typeof AuthenticatedProveedorIndexRoute
  '/api/public/webhooks/floid': typeof ApiPublicWebhooksFloidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tienda': typeof TiendaRoute
  '/plataformas/$slug': typeof PlataformasSlugRoute
  '/plataformas': typeof PlataformasIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/inventario': typeof AuthenticatedAdminInventarioRoute
  '/admin/payouts': typeof AuthenticatedAdminPayoutsRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/pedidos-manuales': typeof AuthenticatedAdminPedidosManualesRoute
  '/admin/productos': typeof AuthenticatedAdminProductosRoute
  '/admin/proveedores': typeof AuthenticatedAdminProveedoresRoute
  '/admin/servicios': typeof AuthenticatedAdminServiciosRoute
  '/admin/stock': typeof AuthenticatedAdminStockRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/ventas': typeof AuthenticatedAdminVentasRoute
  '/proveedor/inventario': typeof AuthenticatedProveedorInventarioRoute
  '/proveedor/perfil': typeof AuthenticatedProveedorPerfilRoute
  '/proveedor/ventas': typeof AuthenticatedProveedorVentasRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/proveedor': typeof AuthenticatedProveedorIndexRoute
  '/api/public/webhooks/floid': typeof ApiPublicWebhooksFloidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tienda': typeof TiendaRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/proveedor': typeof AuthenticatedProveedorRouteWithChildren
  '/plataformas/$slug': typeof PlataformasSlugRoute
  '/plataformas/': typeof PlataformasIndexRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/inventario': typeof AuthenticatedAdminInventarioRoute
  '/_authenticated/admin/payouts': typeof AuthenticatedAdminPayoutsRoute
  '/_authenticated/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/_authenticated/admin/pedidos-manuales': typeof AuthenticatedAdminPedidosManualesRoute
  '/_authenticated/admin/productos': typeof AuthenticatedAdminProductosRoute
  '/_authenticated/admin/proveedores': typeof AuthenticatedAdminProveedoresRoute
  '/_authenticated/admin/servicios': typeof AuthenticatedAdminServiciosRoute
  '/_authenticated/admin/stock': typeof AuthenticatedAdminStockRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/admin/ventas': typeof AuthenticatedAdminVentasRoute
  '/_authenticated/proveedor/inventario': typeof AuthenticatedProveedorInventarioRoute
  '/_authenticated/proveedor/perfil': typeof AuthenticatedProveedorPerfilRoute
  '/_authenticated/proveedor/ventas': typeof AuthenticatedProveedorVentasRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/proveedor/': typeof AuthenticatedProveedorIndexRoute
  '/api/public/webhooks/floid': typeof ApiPublicWebhooksFloidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/tienda'
    | '/admin'
    | '/proveedor'
    | '/plataformas/$slug'
    | '/plataformas/'
    | '/admin/analytics'
    | '/admin/inventario'
    | '/admin/payouts'
    | '/admin/pedidos'
    | '/admin/pedidos-manuales'
    | '/admin/productos'
    | '/admin/proveedores'
    | '/admin/servicios'
    | '/admin/stock'
    | '/admin/usuarios'
    | '/admin/ventas'
    | '/proveedor/inventario'
    | '/proveedor/perfil'
    | '/proveedor/ventas'
    | '/admin/'
    | '/proveedor/'
    | '/api/public/webhooks/floid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/tienda'
    | '/plataformas/$slug'
    | '/plataformas'
    | '/admin/analytics'
    | '/admin/inventario'
    | '/admin/payouts'
    | '/admin/pedidos'
    | '/admin/pedidos-manuales'
    | '/admin/productos'
    | '/admin/proveedores'
    | '/admin/servicios'
    | '/admin/stock'
    | '/admin/usuarios'
    | '/admin/ventas'
    | '/proveedor/inventario'
    | '/proveedor/perfil'
    | '/proveedor/ventas'
    | '/admin'
    | '/proveedor'
    | '/api/public/webhooks/floid'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/sitemap.xml'
    | '/tienda'
    | '/_authenticated/admin'
    | '/_authenticated/proveedor'
    | '/plataformas/$slug'
    | '/plataformas/'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/inventario'
    | '/_authenticated/admin/payouts'
    | '/_authenticated/admin/pedidos'
    | '/_authenticated/admin/pedidos-manuales'
    | '/_authenticated/admin/productos'
    | '/_authenticated/admin/proveedores'
    | '/_authenticated/admin/servicios'
    | '/_authenticated/admin/stock'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/admin/ventas'
    | '/_authenticated/proveedor/inventario'
    | '/_authenticated/proveedor/perfil'
    | '/_authenticated/proveedor/ventas'
    | '/_authenticated/admin/'
    | '/_authenticated/proveedor/'
    | '/api/public/webhooks/floid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TiendaRoute: typeof TiendaRoute
  PlataformasSlugRoute: typeof PlataformasSlugRoute
  PlataformasIndexRoute: typeof PlataformasIndexRoute
  ApiPublicWebhooksFloidRoute: typeof ApiPublicWebhooksFloidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tienda': {
      id: '/tienda'
      path: '/tienda'
      fullPath: '/tienda'
      preLoaderRoute: typeof TiendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proveedor': {
      id: '/_authenticated/proveedor'
      path: '/proveedor'
      fullPath: '/proveedor'
      preLoaderRoute: typeof AuthenticatedProveedorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/plataformas/': {
      id: '/plataformas/'
      path: '/plataformas'
      fullPath: '/plataformas/'
      preLoaderRoute: typeof PlataformasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plataformas/$slug': {
      id: '/plataformas/$slug'
      path: '/plataformas/$slug'
      fullPath: '/plataformas/$slug'
      preLoaderRoute: typeof PlataformasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/inventario': {
      id: '/_authenticated/admin/inventario'
      path: '/inventario'
      fullPath: '/admin/inventario'
      preLoaderRoute: typeof AuthenticatedAdminInventarioRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/payouts': {
      id: '/_authenticated/admin/payouts'
      path: '/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AuthenticatedAdminPayoutsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/pedidos': {
      id: '/_authenticated/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AuthenticatedAdminPedidosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/pedidos-manuales': {
      id: '/_authenticated/admin/pedidos-manuales'
      path: '/pedidos-manuales'
      fullPath: '/admin/pedidos-manuales'
      preLoaderRoute: typeof AuthenticatedAdminPedidosManualesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/productos': {
      id: '/_authenticated/admin/productos'
      path: '/productos'
      fullPath: '/admin/productos'
      preLoaderRoute: typeof AuthenticatedAdminProductosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/proveedores': {
      id: '/_authenticated/admin/proveedores'
      path: '/proveedores'
      fullPath: '/admin/proveedores'
      preLoaderRoute: typeof AuthenticatedAdminProveedoresRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/servicios': {
      id: '/_authenticated/admin/servicios'
      path: '/servicios'
      fullPath: '/admin/servicios'
      preLoaderRoute: typeof AuthenticatedAdminServiciosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/stock': {
      id: '/_authenticated/admin/stock'
      path: '/stock'
      fullPath: '/admin/stock'
      preLoaderRoute: typeof AuthenticatedAdminStockRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/ventas': {
      id: '/_authenticated/admin/ventas'
      path: '/ventas'
      fullPath: '/admin/ventas'
      preLoaderRoute: typeof AuthenticatedAdminVentasRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/proveedor/': {
      id: '/_authenticated/proveedor/'
      path: '/'
      fullPath: '/proveedor/'
      preLoaderRoute: typeof AuthenticatedProveedorIndexRouteImport
      parentRoute: typeof AuthenticatedProveedorRoute
    }
    '/_authenticated/proveedor/inventario': {
      id: '/_authenticated/proveedor/inventario'
      path: '/inventario'
      fullPath: '/proveedor/inventario'
      preLoaderRoute: typeof AuthenticatedProveedorInventarioRouteImport
      parentRoute: typeof AuthenticatedProveedorRoute
    }
    '/_authenticated/proveedor/perfil': {
      id: '/_authenticated/proveedor/perfil'
      path: '/perfil'
      fullPath: '/proveedor/perfil'
      preLoaderRoute: typeof AuthenticatedProveedorPerfilRouteImport
      parentRoute: typeof AuthenticatedProveedorRoute
    }
    '/_authenticated/proveedor/ventas': {
      id: '/_authenticated/proveedor/ventas'
      path: '/ventas'
      fullPath: '/proveedor/ventas'
      preLoaderRoute: typeof AuthenticatedProveedorVentasRouteImport
      parentRoute: typeof AuthenticatedProveedorRoute
    }
    '/api/public/webhooks/floid': {
      id: '/api/public/webhooks/floid'
      path: '/api/public/webhooks/floid'
      fullPath: '/api/public/webhooks/floid'
      preLoaderRoute: typeof ApiPublicWebhooksFloidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminInventarioRoute: typeof AuthenticatedAdminInventarioRoute
  AuthenticatedAdminPayoutsRoute: typeof AuthenticatedAdminPayoutsRoute
  AuthenticatedAdminPedidosRoute: typeof AuthenticatedAdminPedidosRoute
  AuthenticatedAdminPedidosManualesRoute: typeof AuthenticatedAdminPedidosManualesRoute
  AuthenticatedAdminProductosRoute: typeof AuthenticatedAdminProductosRoute
  AuthenticatedAdminProveedoresRoute: typeof AuthenticatedAdminProveedoresRoute
  AuthenticatedAdminServiciosRoute: typeof AuthenticatedAdminServiciosRoute
  AuthenticatedAdminStockRoute: typeof AuthenticatedAdminStockRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminVentasRoute: typeof AuthenticatedAdminVentasRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
    AuthenticatedAdminInventarioRoute: AuthenticatedAdminInventarioRoute,
    AuthenticatedAdminPayoutsRoute: AuthenticatedAdminPayoutsRoute,
    AuthenticatedAdminPedidosRoute: AuthenticatedAdminPedidosRoute,
    AuthenticatedAdminPedidosManualesRoute:
      AuthenticatedAdminPedidosManualesRoute,
    AuthenticatedAdminProductosRoute: AuthenticatedAdminProductosRoute,
    AuthenticatedAdminProveedoresRoute: AuthenticatedAdminProveedoresRoute,
    AuthenticatedAdminServiciosRoute: AuthenticatedAdminServiciosRoute,
    AuthenticatedAdminStockRoute: AuthenticatedAdminStockRoute,
    AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
    AuthenticatedAdminVentasRoute: AuthenticatedAdminVentasRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedProveedorRouteChildren {
  AuthenticatedProveedorInventarioRoute: typeof AuthenticatedProveedorInventarioRoute
  AuthenticatedProveedorPerfilRoute: typeof AuthenticatedProveedorPerfilRoute
  AuthenticatedProveedorVentasRoute: typeof AuthenticatedProveedorVentasRoute
  AuthenticatedProveedorIndexRoute: typeof AuthenticatedProveedorIndexRoute
}

const AuthenticatedProveedorRouteChildren: AuthenticatedProveedorRouteChildren =
  {
    AuthenticatedProveedorInventarioRoute:
      AuthenticatedProveedorInventarioRoute,
    AuthenticatedProveedorPerfilRoute: AuthenticatedProveedorPerfilRoute,
    AuthenticatedProveedorVentasRoute: AuthenticatedProveedorVentasRoute,
    AuthenticatedProveedorIndexRoute: AuthenticatedProveedorIndexRoute,
  }

const AuthenticatedProveedorRouteWithChildren =
  AuthenticatedProveedorRoute._addFileChildren(
    AuthenticatedProveedorRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedProveedorRoute: typeof AuthenticatedProveedorRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedProveedorRoute: AuthenticatedProveedorRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TiendaRoute: TiendaRoute,
  PlataformasSlugRoute: PlataformasSlugRoute,
  PlataformasIndexRoute: PlataformasIndexRoute,
  ApiPublicWebhooksFloidRoute: ApiPublicWebhooksFloidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
